import{S as f,i as l}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const m="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEjSURBVHgBzVWBDYIwEDw3YAM7ghvICG6AG8gGuIFuwAjECRjBEXQD3eB9zCEf0lpASLzkE/iv99/eWYB/gogcNDIsASU+S4cT5oQSOhKXDTmfHeaCklUaNzZKNB4aNeaAEu05cWZyOXMpfgUnv3nyV9YSTIX++MhJt3zftztppmetwBRYYfm+My5Kmauoh8NY0DEft/QabM0Q4wU3ZIXJbfoNmC9GC+4T1hxZg7XJJxIwQog879vS1N7w5FvB8xi54zQlBu7M1GrqkXxrUFphAyQVwsM1OCGyYJqvERG83b588bSYP1qg7r+nxHPfBMhlxLqsTbghNhvagGvrj+DS3TcOEcSOyKzr7ik+lJgZdORjRUFSLIP7ikezxIf8qXHB0ngB0x4XMNg0o7IAAAAASUVORK5CYII=",d="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEaSURBVHgBrZZhDoIwDIUL0fjXo3gUb7R5Er0BHsXD7A+bASlhYeC6V4WXGCHr3reNtkAkqG2D9T70mh/HSj4HybyqyPQ9PeuaXlRQ19GFY4c5dDodLSHNK3/fSam29Q+0k7/N1ZAt5hCyh7kIKZl77y/IMBezgEwXTW4ienBxcc65DCQ0PDYCQghGMDASJJpzTG4ue0KABEHmKeBAQEPx3LiIhmKy/M+aitDyGJoPAWsI32vNWTXpVQnXRal2kPQmO7pPx6XpPRCQmsdjSZ8JhIA0FbOllMKsRZqCQoMpXCy0GJRrFc7hVpGLSVqFWaxk52ZnVgPbIaL5HhBovgVSMv+qg7kt9JznZ+VL//pL+5hWFXei+mwRj+UDSHQ9vnHBEYAAAAAASUVORK5CYII=";function y(r){if(r===void 0)return;console.log(r);const{hits:s}=r,o=document.querySelector(".photos-list"),n=s.map(({downloads:t,comments:a,views:A,likes:u,tags:p,webformatURL:g,largeImageURL:h})=>`
    <li class="gallery">
      <a class="gallery-link" href="${h}"><img src="${g}" alt="${p}" loading="lazy">
      <div class="gallery-wrap"><span class="span">Likes <span class="value">${u}</span></span>
      <span class="span">Views <span class="value">${A}</span></span>
      <span class="span">Comments <span class="value">${a}</span></span>
      <span class="span">Downloads <span class="value">${t}</span></span></div></a>
    </li>`).join("");i(),o.insertAdjacentHTML("beforeend",n),new f(".gallery a").refresh()}function i(){const r=document.querySelector(".photos-list");return r.innerHTML=""}function S(r){const s="44930216-c8fe7065044399c3ab26c911d",o="https://pixabay.com/api/",n=new URLSearchParams({q:r,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`${o}?key=${s}&${n}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{if(e.hits.length===0){i(),l.error({position:"topRight",title:"Sorry, there are no images matching",message:"your search query. Please try again!",titleColor:"white",titleSize:"16px",messageColor:"white",backgroundColor:"#ef4040",iconUrl:d,layout:2,progressBarColor:"#b51b1b",maxWidth:"432px"});return}return e}).catch(e=>console.error(e))}const c={form:document.querySelector(".js-form"),spinner:document.querySelector(".js-loader")};c.form.addEventListener("submit",w);function w(r){r.preventDefault();const s={};if(new FormData(r.target).forEach((o,n)=>s[n]=o.trim().toLowerCase()),!s.textValue){l.info({position:"topRight",title:"It is can not be empty",message:"you must to write something in the stroke",titleColor:"white",titleSize:"16px",messageColor:"white",backgroundColor:"#09f",iconUrl:m,layout:2,progressBarColor:" #3958c9",maxWidth:"432px",closeOnEscape:!0});return}i(),C(),S(s.textValue).then(o=>y(o)).finally(()=>{B()}),r.currentTarget.reset()}function C(){return c.spinner.classList.remove("hidden")}function B(){return c.spinner.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
