import{S as L,a as A,i as p}from"./assets/vendor-ee72e1a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const w="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEjSURBVHgBzVWBDYIwEDw3YAM7ghvICG6AG8gGuIFuwAjECRjBEXQD3eB9zCEf0lpASLzkE/iv99/eWYB/gogcNDIsASU+S4cT5oQSOhKXDTmfHeaCklUaNzZKNB4aNeaAEu05cWZyOXMpfgUnv3nyV9YSTIX++MhJt3zftztppmetwBRYYfm+My5Kmauoh8NY0DEft/QabM0Q4wU3ZIXJbfoNmC9GC+4T1hxZg7XJJxIwQog879vS1N7w5FvB8xi54zQlBu7M1GrqkXxrUFphAyQVwsM1OCGyYJqvERG83b588bSYP1qg7r+nxHPfBMhlxLqsTbghNhvagGvrj+DS3TcOEcSOyKzr7ik+lJgZdORjRUFSLIP7ikezxIf8qXHB0ngB0x4XMNg0o7IAAAAASUVORK5CYII=";function g(t){const r=document.querySelector(".photos-list"),o=t.map(({downloads:e,comments:s,views:l,likes:f,tags:y,webformatURL:S,largeImageURL:b})=>`
    <li class="gallery">
      <a class="gallery-link" href="${b}"><img src="${S}" alt="${y}" loading="lazy">
      <div class="gallery-wrap"><span class="span">Likes <span class="value">${f}</span></span>
      <span class="span">Views <span class="value">${l}</span></span>
      <span class="span">Comments <span class="value">${s}</span></span>
      <span class="span">Downloads <span class="value">${e}</span></span></div></a>
    </li>`).join("");r.insertAdjacentHTML("beforeend",o),new L(".gallery a").refresh()}function u(){const t=document.querySelector(".photos-list");return t.innerHTML=""}const C="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEaSURBVHgBrZZhDoIwDIUL0fjXo3gUb7R5Er0BHsXD7A+bASlhYeC6V4WXGCHr3reNtkAkqG2D9T70mh/HSj4HybyqyPQ9PeuaXlRQ19GFY4c5dDodLSHNK3/fSam29Q+0k7/N1ZAt5hCyh7kIKZl77y/IMBezgEwXTW4ienBxcc65DCQ0PDYCQghGMDASJJpzTG4ue0KABEHmKeBAQEPx3LiIhmKy/M+aitDyGJoPAWsI32vNWTXpVQnXRal2kPQmO7pPx6XpPRCQmsdjSZ8JhIA0FbOllMKsRZqCQoMpXCy0GJRrFc7hVpGLSVqFWaxk52ZnVgPbIaL5HhBovgVSMv+qg7kt9JznZ+VL//pL+5hWFXei+mwRj+UDSHQ9vnHBEYAAAAAASUVORK5CYII=",B="44930216-c8fe7065044399c3ab26c911d",I="https://pixabay.com",v="api/";A.defaults.baseURL=I;async function h({q:t="",page:r=1,per_page:o=15}={}){try{const e=await(await A.get(v,{params:{key:B,q:t,page:r,per_page:o,image_type:"photo",orientation:"horizontal",safesearch:"true"}})).data;if(e.length===0){u(),p.error({position:"topRight",title:"Sorry, there are no images matching",message:"your search query. Please try again!",titleColor:"white",titleSize:"16px",messageColor:"white",backgroundColor:"#ef4040",iconUrl:C,layout:2,progressBarColor:"#b51b1b",maxWidth:"432px"});return}return e}catch(n){console.log(n)}}const a={form:document.querySelector(".js-form"),spinner:document.querySelector(".js-loader"),btnMore:document.querySelector(".js-btn-more")},c="hidden",i={q:"",page:1,per_page:15,maxPage:0};a.form.addEventListener("submit",E);async function E(t){t.preventDefault(),i.page=1;const r=t.currentTarget;if(i.q=r.elements.textValue.value.trim(),!i.q){p.info({position:"topRight",title:"It is can not be empty",message:"you must to write something in the stroke",titleColor:"white",titleSize:"16px",messageColor:"white",backgroundColor:"#09f",iconUrl:w,layout:2,progressBarColor:" #3958c9",maxWidth:"432px",closeOnEscape:!0});return}u(),d();try{const{hits:o,total:n}=await h(i);g(o),o.length>0&&o.length!==n?(a.btnMore.classList.remove(c),a.btnMore.addEventListener("click",x)):a.btnMore.classList.add(c)}catch(o){console.log(o)}finally{m(),r.reset()}}async function x(){a.btnMore.classList.add(c),d(),i.page+=1;try{const{hits:t}=await h(i);g(t)}catch(t){console.log(t)}finally{m(),a.btnMore.classList.remove(c)}}function d(){return a.spinner.classList.remove(c)}function m(){return a.spinner.classList.add(c)}
//# sourceMappingURL=commonHelpers.js.map
